"""Initial migration - fixed constraints

Revision ID: 265533fcf240
Revises: 
Create Date: 2025-10-23 14:28:30.411615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265533fcf240'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('seed_emotion', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_playlist_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider = 'spotify'", name='ck_playlists_provider'),
    sa.CheckConstraint("seed_emotion IN ('joy', 'sadness', 'anger', 'fear', 'disgust', 'surprise', 'neutral')", name='ck_playlists_seed_emotion'),
    sa.CheckConstraint("strategy IN ('maintain', 'change')", name='ck_playlists_strategy'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_playlists_user_created_at_desc', 'playlists', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_table('playlist_tracks',
    sa.Column('playlist_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('track_order', sa.Integer(), nullable=False),
    sa.Column('provider_track_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name='ck_tracks_duration_nonneg'),
    sa.CheckConstraint('track_order > 0', name='ck_tracks_order_pos'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'track_order'),
    sa.UniqueConstraint('playlist_id', 'provider_track_id', name='uq_tracks_playlist_provider_track')
    )
    op.create_index('ix_tracks_playlist_id', 'playlist_tracks', ['playlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracks_playlist_id', table_name='playlist_tracks')
    op.drop_table('playlist_tracks')
    op.drop_index('ix_playlists_user_created_at_desc', table_name='playlists')
    op.drop_table('playlists')
    # ### end Alembic commands ###
